import { useCallback, useEffect, useMemo, useState, type ReactNode } from "react";
import { Activity, BrainCircuit, Check, ChevronRight, Gauge, HeartPulse, Laptop, LoaderCircle, Menu, Package, RefreshCw, Search, ShieldCheck, Smartphone, Sparkles, Users, WandSparkles, Wifi, WifiOff } from "lucide-react";

type Product = { product_id: string; category: string; brand: string; name: string; price_usd: number; ram_gb?: number; storage_gb?: number; display_type?: string; refresh_rate_hz?: number; interaction_count: number };
type Health = { status: string; database: boolean; models_loaded: boolean; mlflow: boolean; products_count: number; version: string };
type Stats = { n_products: number; n_users: number; n_interactions: number; n_laptops: number; n_smartphones: number };
type Drift = { dataset_drift_detected: boolean; share_drifted_columns: number; n_drifted_columns: number; n_total_columns: number };
type Recommendation = { product_id: string; name: string; category: string; price_usd: number; spec_text: string; als_score: number; tfidf_score: number; spec_match_score: number; final_score: number; reason: string };
type RecommendationResult = { recommendation_mode: string; model_version: string; latency_ms: number; recommendations: Recommendation[] };
const API = import.meta.env.VITE_API_BASE ?? "";
const money = (n: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n * 83);
const compact = (n: number) => new Intl.NumberFormat("en-IN", { notation: "compact", maximumFractionDigits: 1 }).format(n);
async function api<T>(path: string, init?: RequestInit): Promise<T> { const response = await fetch(`${API}${path}`, { ...init, headers: { "Content-Type": "application/json" } }); if (!response.ok) throw new Error((await response.json().catch(() => null))?.detail ?? `Request failed (${response.status})`); return response.json(); }
const specs = (p: Product) => [p.ram_gb && `${p.ram_gb}GB RAM`, p.storage_gb && `${p.storage_gb}GB SSD`, p.display_type, p.refresh_rate_hz && `${p.refresh_rate_hz}Hz`].filter(Boolean).join(" · ") || "AI-ranked electronics";
const phone = (category: string) => category.toLowerCase().includes("smart");

export default function App() {
  const [products, setProducts] = useState<Product[]>([]); const [health, setHealth] = useState<Health | null>(null); const [stats, setStats] = useState<Stats | null>(null); const [drift, setDrift] = useState<Drift | null>(null); const [selected, setSelected] = useState<Product | null>(null); const [category, setCategory] = useState("all"); const [query, setQuery] = useState(""); const [userId, setUserId] = useState("U0001"); const [requirements, setRequirements] = useState(""); const [topK, setTopK] = useState(5); const [result, setResult] = useState<RecommendationResult | null>(null); const [loading, setLoading] = useState(true); const [recommending, setRecommending] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); const [h, p, s, d] = await Promise.allSettled([api<Health>("/api/health"), api<Product[]>("/api/products?limit=100"), api<Stats>("/api/stats"), api<Drift>("/api/drift")]); if (h.status === "fulfilled") setHealth(h.value); else setError("FastAPI is unavailable. Start the backend, then refresh this dashboard."); if (p.status === "fulfilled") { setProducts(p.value); setSelected(current => current ?? p.value[0] ?? null); } if (s.status === "fulfilled") setStats(s.value); if (d.status === "fulfilled") setDrift(d.value); setLoading(false); }, []);
  useEffect(() => { load(); const timer = window.setInterval(load, 30000); return () => clearInterval(timer); }, [load]);
  const displayed = useMemo(() => products.filter(p => (category === "all" || p.category.toLowerCase() === category) && (!query || `${p.brand} ${p.name}`.toLowerCase().includes(query.toLowerCase()))), [products, category, query]);
  const recommend = async () => { if (!selected) return; setRecommending(true); setError(""); try { setResult(await api<RecommendationResult>("/api/recommend", { method: "POST", body: JSON.stringify({ user_id: userId, product_id: selected.product_id, required_specs: requirements, top_k: topK, category: category === "all" ? null : category }) })); } catch (e) { setError(e instanceof Error ? e.message : "Could not generate recommendations."); } finally { setRecommending(false); } };
  const okay = health?.status === "healthy";
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Package size={23}/></div><div><strong>Cart<span>Sense</span></strong><small>Adaptive recommendations</small></div></div><nav>{[[<Menu/>,"Overview"],[<Package/>,"Product catalog"],[<WandSparkles/>,"Get recommendations"],[<Sparkles/>,"Cold-start demo"],[<BrainCircuit/>,"MLOps dashboard"]].map(([icon,label], i) => <button className={i === 0 ? "nav-link active" : "nav-link"} key={String(label)}>{icon}{label}</button>)}</nav><div className="connection-card"><div className="connection-title"><i className={okay ? "status-dot" : "status-dot down"}/>{okay ? "Production ready" : "Connection required"}</div><Connection label="API gateway" ok={!!health}/><Connection label="Database" ok={!!health?.database}/><Connection label="MLflow tracking" ok={!!health?.mlflow}/><Connection label="Recommendation model" ok={!!health?.models_loaded}/><button className="refresh-link" onClick={load}><RefreshCw size={14}/> Check connections</button></div><div className="sidebar-foot">CartSense MLOps<br/><span>Hybrid ALS + content engine</span></div></aside><main>
    <section className="hero"><div><p className="eyebrow">DRIFT-RESILIENT RECOMMENDATION ENGINE</p><h1>Smarter choices.<br/><span>Made personal.</span></h1><p className="hero-copy">Hybrid recommendations for electronics that adapt to customers, product launches, and changing market behaviour.</p></div><div className="hero-art"><Laptop className="hero-laptop"/><Smartphone className="hero-phone"/><i className="orb orb-one"/><i className="orb orb-two"/></div></section>
    <section className="topbar"><div className="online-indicator">{okay ? <Wifi size={16}/> : <WifiOff size={16}/>} {okay ? "Backend connected" : "Backend offline"}</div><span>Live health checks every 30 seconds</span><button onClick={load}><RefreshCw size={17} className={loading ? "spin" : ""}/></button></section>{error && <div className="notice">{error}<button onClick={() => setError("")}>×</button></div>}
    <section className="metrics"><Metric icon={<Package/>} value={stats ? compact(stats.n_products) : "—"} label="Catalog products" hint={`${stats?.n_laptops ?? 0} laptops · ${stats?.n_smartphones ?? 0} phones`}/><Metric icon={<Users/>} value={stats ? compact(stats.n_users) : "—"} label="Customer profiles" hint="Personalized ranking"/><Metric icon={<Activity/>} value={stats ? compact(stats.n_interactions) : "—"} label="Interactions learned" hint="Signals in the model"/><Metric icon={<Gauge/>} value={result ? `${Math.round(result.latency_ms)} ms` : "Live"} label="Inference latency" hint="Real-time scoring"/><Metric icon={<ShieldCheck/>} value={drift?.dataset_drift_detected ? "Watch" : "Normal"} label="Drift status" hint={drift ? `${Math.round(drift.share_drifted_columns * 100)}% features shifted` : "Awaiting baseline"}/></section>
    <div className="workspace"><section className="catalog-panel panel"><div className="panel-head"><div><p className="eyebrow">PRODUCT CATALOG</p><h2>Find an anchor item</h2></div><Search size={18}/></div><label className="search-box"><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search laptops or phones"/></label><div className="filter-row">{["all","laptop","smartphone"].map(c => <button key={c} className={category === c ? "filter active" : "filter"} onClick={() => setCategory(c)}>{c === "all" ? "All" : c === "laptop" ? "Laptops" : "Phones"}</button>)}</div><div className="product-list">{loading ? <div className="empty"><LoaderCircle className="spin"/> Loading catalog…</div> : displayed.map(p => <button key={p.product_id} className={selected?.product_id === p.product_id ? "product-row selected" : "product-row"} onClick={() => { setSelected(p); setResult(null); }}><div className="product-icon">{phone(p.category) ? <Smartphone/> : <Laptop/>}</div><div><strong>{p.name}</strong><span>{specs(p)}</span><b>{money(p.price_usd)}</b></div><ChevronRight size={15}/></button>)}</div></section>
      <section className="center-panel"><div className="panel-head"><div><p className="eyebrow">HYBRID AI ENGINE</p><h2>Recommendation workspace</h2></div><div className="model-chip"><BrainCircuit size={15}/>{health?.version ?? "Connecting"}</div></div><div className="selected-card">{selected ? <><div className="selected-visual">{phone(selected.category) ? <Smartphone size={58}/> : <Laptop size={64}/>}</div><div className="selected-content"><span className="tiny-label">REFERENCE ITEM · {selected.category}</span><h3>{selected.name}</h3><p>{specs(selected)}</p><strong>{money(selected.price_usd)}</strong></div><div className="signal"><Activity size={16}/>{compact(selected.interaction_count)} signals</div></> : <div className="empty">Choose a product to begin.</div>}</div><div className="form-card"><div className="form-grid"><label>Customer ID<input value={userId} onChange={e => setUserId(e.target.value)}/></label><label>Recommendation count<select value={topK} onChange={e => setTopK(Number(e.target.value))}>{[3,5,8,10].map(n => <option key={n}>{n}</option>)}</select></label><label className="wide">What matters most?<input value={requirements} onChange={e => setRequirements(e.target.value)} placeholder="e.g. 32GB RAM, OLED display, excellent battery"/></label></div><button className="primary-action" disabled={!selected || recommending || !okay} onClick={recommend}>{recommending ? <LoaderCircle className="spin"/> : <WandSparkles/>}{recommending ? "Scoring products…" : "Generate personalized recommendations"}</button></div><div className="recommendation-area"><div className="section-heading"><div><p className="eyebrow">{result ? result.recommendation_mode.replaceAll("_", " ") : "READY WHEN YOU ARE"}</p><h2>{result ? `Top picks for ${userId}` : "How CartSense reasons"}</h2></div>{result && <span className="latency">{result.latency_ms.toFixed(0)} ms</span>}</div>{result ? <div className="recommendation-grid">{result.recommendations.map((r,i) => <Reco key={r.product_id} r={r} rank={i+1}/>)}</div> : <div className="engine-story"><Engine icon={<Users/>} title="Collaborative signals" text="ALS learns preferences from similar customers."/><Engine icon={<Search/>} title="Content similarity" text="TF-IDF finds matching specifications."/><Engine icon={<Sparkles/>} title="Requirement match" text="Your stated needs boost suitable picks."/></div>}</div></section>
      <aside className="insights-panel panel"><div className="panel-head"><div><p className="eyebrow">MLOPS PULSE</p><h2>Model trust</h2></div><HeartPulse size={19}/></div><div className="trust-card"><div className="trust-head"><i className={drift?.dataset_drift_detected ? "status-dot down" : "status-dot"}/><b>{drift?.dataset_drift_detected ? "Drift detected" : "System stable"}</b></div><p>{drift?.dataset_drift_detected ? "The data distribution changed. Review retraining." : "Model and data signals are within the current guardrail."}</p><Bar value={(drift?.share_drifted_columns ?? 0) * 100}/><small>{drift ? `${drift.n_drifted_columns} of ${drift.n_total_columns} monitored features shifted` : "No drift run available yet"}</small></div><div className="explanation"><h3><Sparkles size={16}/> Explainable ranking</h3><p>Every recommendation reports the component scores used by the hybrid engine.</p>{result?.recommendations[0] ? <Score r={result.recommendations[0]}/> : <div className="score-placeholder">Generate results to inspect an explanation.</div>}</div><div className="capability-list"><h3>Built-in safeguards</h3><p><Check/> Cold-start fallback for new users and items</p><p><Check/> Drift monitoring and retraining route</p><p><Check/> MLflow experiment tracking</p><p><Check/> API health and database status</p></div></aside></div></main></div>;
}
function Connection({label,ok}:{label:string;ok:boolean}) { return <div className="connection"><i className={ok ? "status-dot" : "status-dot down"}/><span>{label}</span><b>{ok ? "Connected" : "Waiting"}</b></div>; }
function Metric({icon,value,label,hint}:{icon:ReactNode;value:string;label:string;hint:string}) { return <article className="metric"><div className="metric-icon">{icon}</div><div><strong>{value}</strong><span>{label}</span><small>{hint}</small></div></article>; }
function Bar({value}:{value:number}) { return <div className="progress"><i style={{width:`${Math.min(100,value)}%`}}/></div>; }
function Engine({icon,title,text}:{icon:ReactNode;title:string;text:string}) { return <div className="engine-step"><div>{icon}</div><h3>{title}</h3><p>{text}</p></div>; }
function Reco({r,rank}:{r:Recommendation;rank:number}) { return <article className="reco-card"><b className="rank">{rank}</b><div className="reco-icon">{phone(r.category) ? <Smartphone/> : <Laptop/>}</div><h3>{r.name}</h3><p>{r.spec_text}</p><div className="score-line"><span>Hybrid score</span><b>{Math.round(r.final_score*100)}%</b></div><Bar value={r.final_score*100}/><small>{r.reason}</small></article>; }
function Score({r}:{r:Recommendation}) { return <div className="score-rows">{[["Collaborative",r.als_score],["Content similarity",r.tfidf_score],["Requirement fit",r.spec_match_score],["Final hybrid score",r.final_score]].map(([label,value]) => <div className="score" key={String(label)}><div><span>{label}</span><b>{Math.round(Number(value)*100)}%</b></div><Bar value={Number(value)*100}/></div>)}</div>; }
